compilers:
  - description: "C, TASKING VX-toolset for 8051: control program   v6.3r1 Build 19041558"
    match-compiler-exe: "(.*/)?cc51(\\.exe)?"
    match-sources: ".*\\.c"
    match-language: C
    code-insight-target-name: arm
    include-dirs: ["${compiler-exe-dir}/../include"]
    defines-text: "
#define	__BIG_ENDIAN__	1
#define	__BUILD__	19041558
#define	__C51__	1
#define	__CHAR_BIT__	8
#define	__CHAR_MAX	SCHAR_MAX
#define	__CHAR_MIN	SCHAR_MIN
#define	__CORE_C51__	1
#define	__INTPTR_BIT__	16
#define	__INT_BIT__	16
#define	__LITTLE_ENDIAN__	0
#define	__LLONG_BIT__	32
#define	__LONG_BIT__	32
#define	__MISRAC_VERSION__	2004
#define	__MODEL__	's'
#define	__PROF_ENABLE__	0
#define	__PTRDIFF_BIT__	16
#define	__PTRDIFF_MAX	INT16_MAX
#define	__PTRDIFF_MIN	INT16_MIN
#define	__REG__(x)	reg##x
#define	__REVISION__	1
#define	__SFRFILE__(cpu)	<sfr/__REG__(cpu).sfr>
#define	__SHORT_BIT__	16
#define	__SINGLE_FP__	1
#define	__SIZE_BIT__	16
#define	__SIZE_MAX	UINT16_MAX
#define	__SIZE_MIN	0
#define	__STDC_HOSTED__	0
#define	__STDC_NO_ATOMICS__	1
#define	__STDC_NO_THREADS__	1
#define	__STDC_VERSION__	201112L
#define	__STDC__	1
#define	__TASKING__	1
#define	__VERSION__	6003
#define	__VX__	1
#define	__WCHAR_BIT__	16
#define	__WCHAR_MAX	INT16_MAX
#define	__WCHAR_MIN	INT16_MIN
"
  - description: "C, TASKING VX-toolset for ARM Cortex: control program   v6.3r1 Build 19041558"
    match-compiler-exe: "(.*/)?ccarm(\\.exe)?"
    match-sources: ".*\\.c"
    match-language: C
    code-insight-target-name: arm
    include-dirs: ["${compiler-exe-dir}/../include"]
    defines-text: "
#define	__ARM__	1
#define	__BUILD__	19041558
#define	__CARM__	1
#define	__CHAR_BIT__	8
#define	__CHAR_MAX	SCHAR_MAX
#define	__CHAR_MIN	SCHAR_MIN
#define	__CPU_ARMV7M__	1
#define	__CPU__	ARMv7M
#define	__DOUBLE_FP__	1
#define	__FPU_NONE__	1
#define	__INTPTR_BIT__	32
#define	__INT_BIT__	32
#define	__LITTLE_ENDIAN__	1
#define	__LLONG_BIT__	64
#define	__LONG_BIT__	32
#define	__MISRAC_VERSION__	2004
#define	__PRECISE_LIB_FP__	1
#define	__PROF_ENABLE__	0
#define	__PTRDIFF_BIT__	32
#define	__PTRDIFF_MAX	INT32_MAX
#define	__PTRDIFF_MIN	INT32_MIN
#define	__REVISION__	1
#define	__SHORT_BIT__	16
#define	__SIZE_BIT__	32
#define	__SIZE_MAX	UINT32_MAX
#define	__SIZE_MIN	0
#define	__STDC_HOSTED__	0
#define	__STDC_NO_ATOMICS__	1
#define	__STDC_NO_THREADS__	1
#define	__STDC_VERSION__	201112L
#define	__STDC__	1
#define	__TASKING__	1
#define	__THUMB2__	1
#define	__VERSION__	6003
#define	__WCHAR_BIT__	16
#define	__WCHAR_MAX	UINT16_MAX
#define	__WCHAR_MIN	0
#define	__WCHAR_UNSIGNED__	1
"
  - description: "C++, TASKING VX-toolset for ARM Cortex: control program   v6.3r1 Build 19041558"
    match-compiler-exe: "(.*/)?ccarm(\\.exe)?"
    match-sources: ".*\\.cpp"
    match-language: CPP
    code-insight-target-name: arm
    include-dirs: ["${compiler-exe-dir}/../include", "${compiler-exe-dir}/../include.cxx"]
    defines-text: "
#define __SIGNED_CHARS__ 1
#define __STDC__ 0
#define __STDC_HOSTED__ 1
#define __cplusplus 201402L
#define _WCHAR_T 1
#define _CPP_WCHAR_T 1
#define __CHAR16_T_AND_CHAR32_T 1
#define _BOOL 1
#define __ARRAY_OPERATORS 1
#define __EXCEPTIONS 1
#define __PLACEMENT_DELETE 1
#define __RUNTIME_USES_NAMESPACES 1
#define __IA64_ABI 1
#define __IA64_ABI_VARIANT_CTORS_AND_DTORS_RETURN_THIS 1
#define __IA64_ABI_USE_INT_STATIC_INIT_GUARD 1
#define __cpp_initializer_lists 200806
#define __cpp_sized_deallocation 201309
#define __cpp_unicode_characters 200704
#define __cpp_aggregate_nsdmi 201304
#define __cpp_alias_templates 200704
#define __cpp_attributes 200809
#define __cpp_binary_literals 201304
#define __cpp_decltype 200707
#define __cpp_decltype_auto 201304
#define __cpp_delegating_constructors 200604
#define __cpp_exceptions 199711
#define __cpp_generic_lambdas 201304
#define __cpp_inheriting_constructors 200802
#define __cpp_init_captures 201304
#define __cpp_lambdas 200907
#define __cpp_nsdmi 200809
#define __cpp_raw_strings 200710
#define __cpp_ref_qualifiers 200710
#define __cpp_return_type_deduction 201304
#define __cpp_rvalue_references 200610
#define __cpp_unicode_literals 200710
#define __cpp_user_defined_literals 200809
#define __cpp_variable_templates 201304
#define __cpp_variadic_templates 200704
#define __cpp_constexpr 201304
#define __cpp_range_based_for 200907
#define __cpp_static_assert 200410
#define __STDC_VERSION__ 199901L
#define __NAMESPACES 1
#define __TYPE_TRAITS_ENABLED 1
#define __VARIADIC_TEMPLATES 1
#define __EDG_CONSTEXPR_ENABLED__ 1
#define __EDG__ 1
#define __EDG_VERSION__ 414
#define __SIZE_TYPE__ unsigned int
#define __PTRDIFF_TYPE__ int
#define __CPARM__ 1
#define __TASKING__ 1
#define __VERSION__ 6003
#define __REVISION__ 1
#define __BUILD__ 19041558
#define _STLP_NO_IOSTREAMS 1
#define __CHAR_MIN SCHAR_MIN
#define __CHAR_MAX SCHAR_MAX
#define __WCHAR_MIN 0
#define __WCHAR_MAX UINT16_MAX
#define __SIZE_MIN INT32_MIN
#define __SIZE_MAX INT32_MAX
#define __PTRDIFF_MIN 0
#define __PTRDIFF_MAX UINT32_MAX
#define __CHAR_BIT__ 8
#define __SHORT_BIT__ 16
#define __INT_BIT__ 32
#define __LONG_BIT__ 32
#define __LLONG_BIT__ 64
#define __PTRDIFF_BIT__ 32
#define __SIZE_BIT__ 32
#define __WCHAR_BIT__ 16
#define __INTPTR_BIT__ 32
#define __WCHAR_UNSIGNED__ 1
#define __DOUBLE_FP__ 1
#define __CPU__ ARMv7M
#define __CPU_ARMV7M__ 1
#define __THUMB2__ 1
#define __LITTLE_ENDIAN__ 1
"
  - description: "C, TASKING VX-toolset for TriCore: control program   v6.3r1 Build 19041558"
    match-compiler-exe: "(.*/)?cctc(\\.exe)?"
    match-sources: ".*\\.c"
    match-language: C
    code-insight-target-name: arm
    include-dirs: ["${compiler-exe-dir}/../include"]
    defines-text: "
#define	__ACCUM_BIT__	64
#define	__ACCUM_INT_BIT__	17
#define	__ATOMIC_INT_LOCK_FREE__	1
#define	__ATOMIC_LONG_LOCK_FREE__	1
#define	__BUILD__	19041558
#define	__CHAR_BIT__	8
#define	__CHAR_MAX	SCHAR_MAX
#define	__CHAR_MIN	SCHAR_MIN
#define	__CORE_TC13__	1
#define	__CTC__	1
#define	__DSPC_VERSION__	200001L
#define	__DSPC__	1
#define	__FPU__	1
#define	__FRACT_BIT__	32
#define	__INTPTR_BIT__	32
#define	__INT_BIT__	32
#define	__LACCUM_BIT__	64
#define	__LACCUM_INT_BIT__	17
#define	__LFRACT_BIT__	32
#define	__LLONG_BIT__	64
#define	__LONG_BIT__	32
#define	__MISRAC_VERSION__	2004
#define	__PROF_ENABLE__	0
#define	__PTRDIFF_BIT__	32
#define	__PTRDIFF_MAX	INT32_MAX
#define	__PTRDIFF_MIN	INT32_MIN
#define	__REG__(x)	reg##x
#define	__REVISION__	1
#define	__SACCUM_BIT__	64
#define	__SACCUM_INT_BIT__	17
#define	__SFRACT_BIT__	16
#define	__SFRFILE__(cpu)	<sfr/__REG__(cpu).sfr>
#define	__SHORT_BIT__	16
#define	__SINGLE_FP__	1
#define	__SIZE_BIT__	32
#define	__SIZE_MAX	UINT32_MAX
#define	__SIZE_MIN	0
#define	__STDC_HOSTED__	0
#define	__STDC_NO_ATOMICS__	1
#define	__STDC_NO_THREADS__	1
#define	__STDC_VERSION__	201112L
#define	__STDC__	1
#define	__TASKING__	1
#define	__VERSION__	6003
#define	__WCHAR_BIT__	16
#define	__WCHAR_MAX	INT16_MAX
#define	__WCHAR_MIN	INT16_MIN
#define	transpose_byte	__transpose_byte
#define	transpose_hword	__transpose_hword
"
  - description: "C++, TASKING VX-toolset for TriCore: control program   v6.3r1 Build 19041558"
    match-compiler-exe: "(.*/)?cctc(\\.exe)?"
    match-sources: ".*\\.cpp"
    match-language: CPP
    code-insight-target-name: arm
    include-dirs: ["${compiler-exe-dir}/../include", "${compiler-exe-dir}/../include.cxx"]
    defines-text: "
#define __SIGNED_CHARS__ 1
#define __STDC__ 0
#define __STDC_HOSTED__ 1
#define __cplusplus 201402L
#define _WCHAR_T 1
#define _CPP_WCHAR_T 1
#define __CHAR16_T_AND_CHAR32_T 1
#define _BOOL 1
#define __ARRAY_OPERATORS 1
#define __EXCEPTIONS 1
#define __PLACEMENT_DELETE 1
#define __RUNTIME_USES_NAMESPACES 1
#define __IA64_ABI 1
#define __cpp_initializer_lists 200806
#define __cpp_sized_deallocation 201309
#define __cpp_unicode_characters 200704
#define __cpp_aggregate_nsdmi 201304
#define __cpp_alias_templates 200704
#define __cpp_attributes 200809
#define __cpp_binary_literals 201304
#define __cpp_decltype 200707
#define __cpp_decltype_auto 201304
#define __cpp_delegating_constructors 200604
#define __cpp_exceptions 199711
#define __cpp_generic_lambdas 201304
#define __cpp_inheriting_constructors 200802
#define __cpp_init_captures 201304
#define __cpp_lambdas 200907
#define __cpp_nsdmi 200809
#define __cpp_raw_strings 200710
#define __cpp_ref_qualifiers 200710
#define __cpp_return_type_deduction 201304
#define __cpp_rvalue_references 200610
#define __cpp_unicode_literals 200710
#define __cpp_user_defined_literals 200809
#define __cpp_variable_templates 201304
#define __cpp_variadic_templates 200704
#define __cpp_constexpr 201304
#define __cpp_range_based_for 200907
#define __cpp_static_assert 200410
#define __STDC_VERSION__ 199901L
#define __NAMESPACES 1
#define __TYPE_TRAITS_ENABLED 1
#define __VARIADIC_TEMPLATES 1
#define __EDG_CONSTEXPR_ENABLED__ 1
#define __EDG__ 1
#define __EDG_VERSION__ 414
#define __SIZE_TYPE__ unsigned int
#define __PTRDIFF_TYPE__ int
#define __CPTC__ 1
#define __TASKING__ 1
#define __VERSION__ 6003
#define __REVISION__ 1
#define __BUILD__ 19041558
#define _STLP_NO_IOSTREAMS 1
#define __CHAR_MIN SCHAR_MIN
#define __CHAR_MAX SCHAR_MAX
#define __WCHAR_MIN 0
#define __WCHAR_MAX UINT16_MAX
#define __SIZE_MIN INT32_MIN
#define __SIZE_MAX INT32_MAX
#define __PTRDIFF_MIN 0
#define __PTRDIFF_MAX UINT32_MAX
#define __CHAR_BIT__ 8
#define __SHORT_BIT__ 16
#define __INT_BIT__ 32
#define __LONG_BIT__ 32
#define __LLONG_BIT__ 64
#define __PTRDIFF_BIT__ 32
#define __SIZE_BIT__ 32
#define __WCHAR_BIT__ 16
#define __INTPTR_BIT__ 32
#define __WCHAR_UNSIGNED__ 1
#define __SINGLE_FP__ 1
#define __REG__(x) reg ## x
#define __SFRFILE__(cpu) <sfr/__REG__(cpu).sfr>
#define __FPU__ 1
#define __CORE_TC13__ 1
#define __putbit(value,address,bitoffset) __imaskldmst(address,value,bitoffset,1)
#define __getbit(address,bitoffset) __extru(*(address),bitoffset,1)
#define __crc32bw(b,a) __crc32(b,a)
"
